# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
