# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:33
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_auto_20160511_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=catalog.models.make_upload_path, verbose_name='Иконка'),
        ),
    ]
