# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 17:07
from __future__ import unicode_literals

import catalog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_contacts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название статьи')),
                ('article', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('meta_key', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ключевые слова')),
                ('meta_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, default='', max_length=250, verbose_name='УРЛ')),
                ('image', models.ImageField(blank=True, default='', upload_to=catalog.models.make_upload_path, verbose_name='Изображение для заголовка')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
    ]
