# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0004_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.ImageUploader.make_upload_path, verbose_name='Изображение для заголовка'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.ImageUploader.make_upload_path, verbose_name='Иконка'),
        ),
    ]
