# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 12:05
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Категория')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('meta_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='Мета описание')),
                ('meta_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Ключевае слова')),
                ('slug', models.SlugField(blank=True, default='', max_length=250, verbose_name='УРЛ')),
                ('image', models.ImageField(blank=True, default='', upload_to=catalog.models.make_upload_path, verbose_name='Изображение')),
                ('published', models.BooleanField(verbose_name='Опубликовать')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Название')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('meta_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='Мета описание')),
                ('meta_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Ключевае слова')),
                ('slug', models.SlugField(blank=True, default='', max_length=250, verbose_name='УРЛ')),
                ('image', models.ImageField(blank=True, default='', upload_to=catalog.models.make_upload_path, verbose_name='Изображение')),
                ('shot_text', tinymce.models.HTMLField(blank=True, verbose_name='Краткое описание')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('published', models.BooleanField(verbose_name='Опубликовать')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('category', models.ManyToManyField(related_name='cat', to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=catalog.models.make_upload_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Services')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
