# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160506_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
