# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160510_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=250, verbose_name='Размер')),
            ],
            options={
                'verbose_name_plural': 'Размеры',
                'verbose_name': 'Размер',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='material',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='services',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Sizes', verbose_name='Размер'),
        ),
    ]
