# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160519_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, verbose_name='Материал')),
            ],
            options={
                'verbose_name_plural': 'Материалы',
                'verbose_name': 'Материал',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Materials', verbose_name='Материал'),
        ),
    ]
