# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160519_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название'),
        ),
    ]
