# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160520_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
