# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161122_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimages',
            old_name='product',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.ImageUploader.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.ImageUploader.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='servicesimages',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.ImageUploader.make_upload_path, verbose_name='Изображение'),
        ),
    ]
